### PR TITLE
Axbase require modernization.

### PR DESCRIPTION
**Pull request by EatThePath**
Axem's script ecosystem just kind of assumes all the required scripts are present and loaded in the right order. These changes offload the often-used scripts into .lua files so that `require` can be used instead to make it clearer when files are missing from a mod, and changes the relevant scripts to take advantage of this.

Git shenangigans were used to preserve the change history in both the -sct files and the new .lua files.

### CODE REVIEW

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Good idea.  I assume the .lua files are verbatim copies of the script files?

Rather than displaying the message, "ensure AxBase is in mod stack", specify the actual .lua file that is missing.

**Comment by EatThePath** [comment]
> Good idea. I assume the .lua files are verbatim copies of the script files?

They're actually renames, so they still retain the file history if you go into the individual files rather than the overall PR view

> Rather than displaying the message, "ensure AxBase is in mod stack", specify the actual .lua file that is missing.

I chose to go with axBase because that's how you can find the files on the this repo and you'll often need the whole package rather than just one file. If someone grabs a script from this repo without paying attention the requirements, then comes back and searches the front page for axUI or axemParse, they're going to be stumped.

If someone is in need of more specific debugging, then the line number on the error message can point them to what exact require failed.

**Comment by Goober5000** [comment]
> They're actually renames, so they still retain the file history if you go into the individual files rather than the overall PR view

Gotcha

> I chose to go with axBase because that's how you can find the files on the this repo and you'll often need the whole package rather than just one file. If someone grabs a script from this repo without paying attention the requirements, then comes back and searches the front page for axUI or axemParse, they're going to be stumped.

Sure, but an end-user running the mod, or even another modder dissecting one mod to make another, is not necessarily going to know about this repo.

Why not give *both* pieces of information, then, e.g. "the axui.lua file from the AxBase library"?

**Comment by EatThePath** [comment]
> Sure, but an end-user running the mod, or even another modder dissecting one mod to make another, is not necessarily going to know about this repo.
> 
> Why not give _both_ pieces of information, then, e.g. "the axui.lua file from the AxBase library"?

Mainly because anyone equipped to act on that information can get it pretty trivially from looking at the source of the error message.

There's nothing strictly wrong with including that information, but I am not persuaded of it's need and I'd rather just merge this as is and be done with it.

**Review by Goober5000 — APPROVED** [review]
Well, I'm skeptical, based on the SCP's historical experience with error messages, but I'm ok with moving ahead anyway.

**Pull request merged**
